### ISSUE TITLE
Ensure that isort-check gives same results for makefile and pre-commit-hook

### ISSUE THREAD

**Issue by ablech** [qucontrol/qdynpylib#13]
* qdynpylib version: 0.4.0
* Python version: 3.7.3
* Operating System: Ubuntu 18.04

### Description

Currently the isort check performed by the pre-commit-hook reports an error for the file tests/test_io.py while `make isort-check` reports success.

**Comment by goerz** [comment]
Should be fixed now. Please re-open the issue if this doesn't work for you
