### ISSUE TITLE
PendingDeprecationWarning for np.matrix with pytest

### ISSUE THREAD

**Issue by ablech** [qucontrol/qdynpylib#17]
Since commit 14aa0134085355e3b64dc8275f21607552ffdfeb we do no longer use the numpy matrix type. However, `scipy.sparse` uses it in some cases, in particular for the calculation of the norm of a sparse matrix.
(More precisly `scipy.sparse.linalg.norm()` uses the sparse matrix `.sum()` method, which calls `numpy.asmatrix()`).
For this reason, pytest is still generating PendingDeprecationWarnings every time we use `qdyn.linalg.norm()` with a sparse matrix type. Currently all remaining warnings originate from this.

How about filtering out this warnings by adding 
```python
filterwarnings=ignore:the matrix subclass:PendingDeprecationWarning
```
to `setup.cfg` (as suggested in https://github.com/scipy/scipy/issues/9734#issuecomment-459409414)?

Or do you think, it is better to stay reminded not to use them in the future?
Is there another way to prevent people from using the matrix type?

**Comment by goerz** [comment]
Good idea! That warning really is a major annoyance!
